---
title: "Facebook activity reivew"
author: "Luran M."
date: "November 28, 2019"
output:
  html_document:
    highlight: tango
    theme: spacelab
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
  word_document:
    toc: yes
---


```{r, include=FALSE, warning=FALSE}

library(tidyr)
library(dplyr)
library(ggplot2)
library(keyringr)
library(redcapAPI)
library(REDCapR)
library(lubridate)
library(formattable)

# **************************************************************************** #
# ***************  Pull data from redcap with api                                              
# **************************************************************************** # 

# Get Redcap API Token
# # https://cran.r-project.org/web/packages/keyringr/vignettes/Avoiding_plain_text_passwords_in_R_with_keyringr.html
credential_label <- "interview_api"
credential_path <- paste(Sys.getenv("USERPROFILE"), '\\DPAPI\\passwords\\', Sys.info()["nodename"], '\\', credential_label, '.txt', sep="")
uri <- "https://redcap.ctsi.ufl.edu/redcap/api/"
beach_token<-decrypt_dpapi_pw(credential_path)
print(beach_token)

# Create connections
rcon <- redcapConnection(url=uri, token=beach_token)


# crc variables

desired_fields <- c("record_id","int_phone_pass_fail","encounter_date_int","encounter_type_int",
"beach_interview_study_encounters_complete",
"learn_about_study_int","int_consent_complete",
"analysis_mat_age_cats","analysis_bmi","mom3t_education_2",
"analysis_mat_age","analysis_income","analysis_kids_previous")


# events to retain

events_to_retain  <- c("beach_interview_phone_screen","beach_interview_study_encounters")

# list of events

# list records
#exportRecords(rcon)  I don't know why having this in a report is an issue

# export field names

# consented records
records.v1=c("BIS001A","BIS002A","BIS003A","BIS004A","BIS005A",
                     "BIS006A","BIS007A","BIS008A","BIS009A","BIS010A",
                     "BIS011A","BIS013A","BIS014A","BIS018A","BIS019A",
                     "BIS022A","BIS023A","BIS024A","BIS025A","BIS026A",
                     "BIS027A","BIS028A","BIS029A","BIS030A","BIS031A",
                     "BIS032A","BIS033A","BIS034A",
                     "PRG001","PRG002","PRG003","PRG004","PRG005",
                     "PRG006","PRG007","PRG008","PRG009","PRG010",
                     "PRG011","PRG012","PRG013","PRG014","PRG015",
                     "PRG016","PRG017","PRG018","PRG020",
                     "156","157","195","196","214","216","224","225","228",
                     "230","234","235","238","239",
                     "240","241","242","245","246","251","255","257","258",
                     "259","260","261","262","265","266","267",
                     "268","269","270","271","273","274","275","276","277",
                     "278","280","281","282","283","286","289",
                     "290","291","293","294","295","296","297","85","88","90")

ds <- data.frame(records.v1)

# pull data
ds_some_rows_v1 <- redcap_read(
  redcap_uri = uri, 
  records= records.v1,
  token      = beach_token, 
  fields     = desired_fields
  
)$data
```

```{r echo=FALSE, warning=FALSE}
# recode encounter type
ds_some_rows_v1=ds_some_rows_v1 %>%
  #use mutate(new column = recode(current column to be recoded, "variable in column"="new variable name"))
    mutate(learn_about_study = recode(learn_about_study_int, "1"="Flyer","3"="Facebook","5"="Other"))%>%
  replace_na(list( learn_about_study = "Didn't Respond"))%>%
  mutate(education_level = recode(mom3t_education_2,"1"="8th grade or less","2"="some high school","3"="high school diploma/GED","4"="some college or community college","5"="Associates degree","6"="completed tech or vocational school","7"="college graduate","8"="some graduate or professional school","9"="Graduate or professional degree"))%>%
  mutate(previous_kids = recode(analysis_kids_previous, "1"="yes","0"="no"))%>%
  mutate(income = recode(analysis_income, "1"="$0-$15,000","2"="$15,001-$19,000","3"="$19,001-$37,000","4"="$37,001-$44,000","5"="$44,001-$52,000","6"="$52,001-$56,000","7"="$56,001-$67,000","8"="$67,001-$79,000","9"="$79,001 or more"))%>%
  mutate(phone_pass_fail = recode(int_phone_pass_fail, "1"="pass","0"="fail"))%>%
  mutate(consent_complete = recode(int_consent_complete, "1"="Consented","0"="not Consented","NA"="Did not respond"))

```

```{r echo=FALSE, warning=FALSE}
Totals <- ds_some_rows_v1%>%
  select(learn_about_study)%>%
  group_by(learn_about_study)%>%
  summarize(count=n())%>%
  rename("how did you hear about us?"=learn_about_study,"Total"=count)

formattable(Totals, align =c("l","r"))

Monthly_recruitment <- ds_some_rows_v1%>%
  select(learn_about_study,encounter_date_int)%>%
  separate(encounter_date_int,c("y","m","d"))%>%
  unite("YM",c("y","m"),sep ="-")%>%
  group_by(YM)%>%
  summarise(count=n())%>%
  rename("Recruitment for the month"=count,"Month of Recruitment"=YM)


formattable(Monthly_recruitment, align =c("l","r"))
```

```{r, echo=FALSE, warning=FALSE}
Encounter_per_time <- ds_some_rows_v1%>%
  select(encounter_date_int,learn_about_study)

Encounter_per_time$encounter_date_int <- as.Date(Encounter_per_time$encounter_date_int, format= "%Y-%m-%d")

my_data <- data.frame(encounter_date_int = seq(as.Date("2017-01-01"), as.Date("2019-12-31"), 
  by = "1 month"), format= "%Y-%m-%d")

my_complete <- full_join(my_data, Encounter_per_time, by = "encounter_date_int")

Encounter_per_time <- my_complete%>%
  separate(encounter_date_int,c("y","m","d"))%>%
  group_by(learn_about_study,m,y)%>%
  summarize(count=n())%>%
  unite("YM",c("y","m"),sep ="-")


theme_set(theme_classic())
# distribution of visits each month(histogram)
h <- ggplot(Encounter_per_time, aes(YM, count)) + scale_fill_brewer(palette = "Spectral")
h + geom_histogram(aes(fill=factor(learn_about_study)), stat = "Identity",
                   bins=24,
                   col="black", 
                   size=.1) + # change number of bins
  # geom_density() + #this function is meant to draw a trend line for the graph
  # stat_bin(aes(y=count,label=count),geom="text",vjust=-.5) +   # this will display the total count of each bin
  labs(title="How participants heard of our study monthly", 
       subtitle="from july of 2017-January 2019",
       x="Date(Year-Month)",
       y="Count",
       fill="How did you learn about the study") +
  theme(axis.text.x = element_text(angle=70, vjust =.6))
```



```{r echo=FALSE, warning=FALSE}

#------------------------------------------
  #creating the tables for each round of facebook add
#------------------------------------------

Encounter_per_time <- ds_some_rows_v1%>%
  select(encounter_date_int,learn_about_study)

round_1 <- Encounter_per_time%>%
  separate(encounter_date_int,c("y","m","d"))%>%
  filter(y=="2018", m>="03" & m<="05")%>%
  group_by(learn_about_study,m,y)%>%
  summarize(count=n())%>%
  unite("YM",c("y","m"),sep ="-")

round_2 <- Encounter_per_time%>%
  separate(encounter_date_int,c("y","m","d"))%>%
  filter(y=="2018", m>="05" & m<="08")%>%
  group_by(learn_about_study,m,y)%>%
  summarize(count=n())%>%
  unite("YM",c("y","m"),sep ="-")

round_3 <- Encounter_per_time%>%
  separate(encounter_date_int,c("y","m","d"))%>%
  filter(y=="2018", m>="11" & m<="11")%>%
  group_by(learn_about_study,m,y)%>%
  summarize(count=n())%>%
  unite("YM",c("y","m"),sep ="-")

round_4 <- Encounter_per_time%>%
  separate(encounter_date_int,c("y","m","d"))%>%
  filter(y=="2018", m>="11" & m<="12")%>%
  group_by(learn_about_study,m,y)%>%
  summarize(count=n())%>%
  unite("YM",c("y","m"),sep ="-")

round_5 <- Encounter_per_time%>%
  separate(encounter_date_int,c("y","m","d"))%>%
  filter(y=="2019", m>="02" & m<="02")%>%
  group_by(learn_about_study,m,y)%>%
  summarize(count=n())%>%
  unite("YM",c("y","m"),sep ="-")

round_6 <- Encounter_per_time%>%
  separate(encounter_date_int,c("y","m","d"))%>%
  filter(y=="2019", m>="04" & m<="05")%>%
  group_by(learn_about_study,m,y)%>%
  summarize(count=n())%>%
  unite("YM",c("y","m"),sep ="-")

round_7 <- Encounter_per_time%>%
  separate(encounter_date_int,c("y","m","d"))%>%
  filter(y=="2019", m>="09" & m<="10")%>%
  group_by(learn_about_study,m,y)%>%
  summarize(count=n())%>%
  unite("YM",c("y","m"),sep ="-")
```


```{r echo=FALSE, warning=FALSE}
#------------------------------------------
  #creating the graphs for each round of facebook add
#------------------------------------------

theme_set(theme_classic())
# distribution of visits each month(histogram)
h <- ggplot(round_1, aes(YM, count)) + scale_fill_brewer(palette = "Spectral")
h + geom_histogram(aes(fill=factor(learn_about_study)), stat = "Identity",
                   bins=24,
                   col="black", 
                   size=.1) + # change number of bins
  # geom_density() + #this function is meant to draw a trend line for the graph
  # stat_bin(aes(y=count,label=count),geom="text",vjust=-.5) +   # this will display the total count of each bin
  labs(title="Recruitment for Round 1 Facebook adds", 
       subtitle="3 months of add, March 2018-May 2018",
       x="Date(Year-Month)",
       y="Count",
       fill="How did you learn about the study") +
  theme(axis.text.x = element_text(angle=70, vjust =.6))


#formattable(Encounter_per_time,align=c("l","c","c","r"))

theme_set(theme_classic())
# distribution of visits each month(histogram)
h <- ggplot(round_2, aes(YM, count)) + scale_fill_brewer(palette = "Spectral")
h + geom_histogram(aes(fill=factor(learn_about_study)), stat = "Identity",
                   bins=24,
                   col="black", 
                   size=.1) + # change number of bins
  # geom_density() + #this function is meant to draw a trend line for the graph
  # stat_bin(aes(y=count,label=count),geom="text",vjust=-.5) +   # this will display the total count of each bin
  labs(title="Recruitment for Round 2 Facebook adds", 
       subtitle="2 months of add, May 2018-August 2018",
       x="Date(Year-Month)",
       y="Count",
       fill="How did you learn about the study") +
  theme(axis.text.x = element_text(angle=70, vjust =.6))


#formattable(Encounter_per_time,align=c("l","c","c","r"))

theme_set(theme_classic())
# distribution of visits each month(histogram)
h <- ggplot(round_3, aes(YM, count)) + scale_fill_brewer(palette = "Spectral")
h + geom_histogram(aes(fill=factor(learn_about_study)), stat = "Identity",
                   bins=24,
                   col="black", 
                   size=.1) + # change number of bins
  # geom_density() + #this function is meant to draw a trend line for the graph
  # stat_bin(aes(y=count,label=count),geom="text",vjust=-.5) +   # this will display the total count of each bin
  labs(title="Recruitment for Round 3 Facebook adds", 
       subtitle="1 months of add, November 2018-November 2018",
       x="Date(Year-Month)",
       y="Count",
       fill="How did you learn about the study") +
  theme(axis.text.x = element_text(angle=70, vjust =.6))


#formattable(Encounter_per_time,align=c("l","c","c","r"))

theme_set(theme_classic())
# distribution of visits each month(histogram)
h <- ggplot(round_4, aes(YM, count)) + scale_fill_brewer(palette = "Spectral")
h + geom_histogram(aes(fill=factor(learn_about_study)), stat = "Identity",
                   bins=24,
                   col="black", 
                   size=.1) + # change number of bins
  # geom_density() + #this function is meant to draw a trend line for the graph
  # stat_bin(aes(y=count,label=count),geom="text",vjust=-.5) +   # this will display the total count of each bin
  labs(title="Recruitment for Round 4 Facebook adds", 
       subtitle="2 months of add, November 2018-December 2018",
       x="Date(Year-Month)",
       y="Count",
       fill="How did you learn about the study") +
  theme(axis.text.x = element_text(angle=70, vjust =.6))


#formattable(Encounter_per_time,align=c("l","c","c","r"))

theme_set(theme_classic())
# distribution of visits each month(histogram)
h <- ggplot(round_5, aes(YM, count)) + scale_fill_brewer(palette = "Spectral")
h + geom_histogram(aes(fill=factor(learn_about_study)), stat = "Identity",
                   bins=24,
                   col="black", 
                   size=.1) + # change number of bins
  # geom_density() + #this function is meant to draw a trend line for the graph
  # stat_bin(aes(y=count,label=count),geom="text",vjust=-.5) +   # this will display the total count of each bin
  labs(title="Recruitment for Round 5 Facebook adds", 
       subtitle="1 months of add, February 2019-February 2019",
       x="Date(Year-Month)",
       y="Count",
       fill="How did you learn about the study") +
  theme(axis.text.x = element_text(angle=70, vjust =.6))


#formattable(Encounter_per_time,align=c("l","c","c","r"))

theme_set(theme_classic())
# distribution of visits each month(histogram)
h <- ggplot(round_6, aes(YM, count)) + scale_fill_brewer(palette = "Spectral")
h + geom_histogram(aes(fill=factor(learn_about_study)), stat = "Identity",
                   bins=24,
                   col="black", 
                   size=.1) + # change number of bins
  # geom_density() + #this function is meant to draw a trend line for the graph
  # stat_bin(aes(y=count,label=count),geom="text",vjust=-.5) +   # this will display the total count of each bin
  labs(title="Recruitment for Round 6 Facebook adds", 
       subtitle="2 months of add, April 2019-May 2019",
       x="Date(Year-Month)",
       y="Count",
       fill="How did you learn about the study") +
  theme(axis.text.x = element_text(angle=70, vjust =.6))


#formattable(Encounter_per_time,align=c("l","c","c","r"))

theme_set(theme_classic())
# distribution of visits each month(histogram)
h <- ggplot(round_7, aes(YM, count)) + scale_fill_brewer(palette = "Spectral")
h + geom_histogram(aes(fill=factor(learn_about_study)), stat = "Identity",
                   bins=24,
                   col="black", 
                   size=.1) + # change number of bins
  # geom_density() + #this function is meant to draw a trend line for the graph
  # stat_bin(aes(y=count,label=count),geom="text",vjust=-.5) +   # this will display the total count of each bin
  labs(title="Recruitment for Round 7 Facebook adds", 
       subtitle="2 months of add, September 2019-October 2019",
       x="Date(Year-Month)",
       y="Count",
       fill="How did you learn about the study") +
  theme(axis.text.x = element_text(angle=70, vjust =.6))


#formattable(Encounter_per_time,align=c("l","c","c","r"))



```