---
title: "Redcap Data report"
author: "Luran M."
date: "September 5, 2019"
output: 
  html_document:
    theme: spacelab
    highlight: tango
    toc: true
    toc_float: true
---


```{r, include=FALSE}

library(tidyr)
library(dplyr)
library(ggplot2)
library(keyringr)
library(redcapAPI)
library(REDCapR)
library(lubridate)


# **************************************************************************** #
# ***************  Pull data from redcap with api                                              
# **************************************************************************** # 

# Get Redcap API Token
# # https://cran.r-project.org/web/packages/keyringr/vignettes/Avoiding_plain_text_passwords_in_R_with_keyringr.html
credential_label <- "beach_interview_api"
credential_path <- paste(Sys.getenv("USERPROFILE"), '\\DPAPI\\passwords\\', Sys.info()["nodename"], '\\', credential_label, '.txt', sep="")
uri <- "https://redcap.ctsi.ufl.edu/redcap/api/"
beach_token<-decrypt_dpapi_pw(credential_path)
print(beach_token)

# Create connections
rcon <- redcapConnection(url=uri, token=beach_token)


# crc variables
fields <- exportFieldNames(rcon)
desired_fields <- c("record_id","int_phone_pass_fail","encounter_date_int","encounter_type_int",
"beach_interview_study_encounters_complete",
"learn_about_study_int","int_consent_complete",
"analysis_mat_age_cats","analysis_bmi","mom3t_education_2",
"analysis_mat_age","analysis_income","analysis_kids_previous")


# events to retain
exportEvents(rcon)
events_to_retain  <- c("beach_interview_phone_screen","beach_interview_study_encounters")

# list of events
exportEvents(rcon)

# list records
#exportRecords(rcon)  I don't know why having this in a report is an issue

# export field names
exportFieldNames(rcon)

# consented records
consent.records.v1=c("BIS001A","BIS002A","BIS003A","BIS004A","BIS005A",
                     "BIS006A","BIS007A","BIS008A","BIS009A","BIS010A",
                     "BIS011A","BIS013A","BIS014A","BIS018A","BIS019A",
                     "BIS022A","BIS023A","BIS024A","BIS025A","BIS026A",
                     "BIS027A","BIS028A","BIS029A","BIS030A","BIS031A",
                     "BIS032A","BIS033A","BIS034A",
                     "PRG001","PRG002","PRG003","PRG004","PRG005",
                     "PRG006","PRG007","PRG008","PRG009","PRG010",
                     "PRG011","PRG012","PRG013","PRG014","PRG015",
                     "PRG016","PRG017","PRG018","PRG020",
                     "156","157","195","196","214","216","224","225","228",
                     "230","234","235","238","239",
                     "240","241","242","245","246","251","255","257","258",
                     "259","260","261","262","265","266","267",
                     "268","269","270","271","273","274","275","276","277",
                     "278","280","281","282","283","286","289",
                     "290","291","293","294","295","296","297","85","88","90")

# pull data
ds_some_rows_v1 <- redcap_read(
  redcap_uri = uri, 
  records= consent.records.v1,
  token      = beach_token, 
  fields     = desired_fields
  
)$data

# recode encounter type
ds_some_rows_v1=ds_some_rows_v1 %>%
  #use mutate(new column = recode(current column to be recoded, "variable in column"="new variable name"))
    mutate(learn_about_study = recode(learn_about_study_int, "1"="Flyer","3"="Facebook","5"="Other"))%>%
  mutate(education_level = recode(mom3t_education_2,"1"="8th grade or less","2"="some high school","3"="high school diploma/GED","4"="some college or community college","5"="Associates degree","6"="completed tech or vocational school","7"="college graduate","8"="some graduate or professional school","9"="Graduate or professional degree"))%>%
  mutate(previous_kids = recode(analysis_kids_previous, "1"="yes","0"="no"))%>%
  mutate(income = recode(analysis_income, "1"="$0-$15,000","2"="$15,001-$19,000","3"="$19,001-$37,000","4"="$37,001-$44,000","5"="$44,001-$52,000","6"="$52,001-$56,000","7"="$56,001-$67,000","8"="$67,001-$79,000","9"="$79,001 or more"))

```


## Figures Plots of Total Encounters
```{r, echo=FALSE}
Totals <- ds_some_rows_v1%>%
  select(learn_about_study)%>%
  group_by(learn_about_study)%>%
  summarize(count=n())%>%
  rename("how did you hear about us?"=learn_about_study)

print(Totals)
```

##Encounters Over Time
###Total Encounters
```{r, echo=FALSE}
Encounter_per_Time <- ds_some_rows_v1%>%
  separate(encounter_date_int,c("y","m","d"))%>%
  group_by(learn_about_study,m,y)%>%
  summarize(count=n())%>%
  unite("YM",c("y","m"),sep ="-")
    
theme_set(theme_classic())

# distribution of visits each month(histogram)
h <- ggplot(Encounter_per_Time, aes(YM, count)) + scale_fill_brewer(palette = "Spectral")
h + geom_histogram(aes(fill=factor(learn_about_study)), stat = "Identity",
                   bins=24,
                   col="black", 
                   size=.1) + # change number of bins
  # geom_density() + #this function is meant to draw a trend line for the graph
  # stat_bin(aes(y=count,label=count),geom="text",vjust=-.5) +   # this will display the total count of each bin
  labs(title="How participants heard of our study monthly", 
       subtitle="from july of 2017-January 2019",
       x="Date(Year-Month)",
       y="Count",
       fill="How did you learn about the study") +
  theme(axis.text.x = element_text(angle=70, vjust =.6))

```
###Passed Participants
```{r, echo=FALSE}
# provides the number of total passed participants per month per encounter type(how they learned about our study) 
total_pass <- ds_some_rows_v1%>%
  select(int_phone_pass_fail,learn_about_study,encounter_date_int)%>%
  separate(encounter_date_int,c("y","m","d"))%>%
  filter(int_phone_pass_fail==1)%>%
  group_by(m,y,int_phone_pass_fail,learn_about_study)%>%
  summarize(count=n())%>%
  unite("YM",c("y","m"),sep ="-")

print(total_pass)

t <- ggplot(total_pass, aes(YM, count, int_phone_pass_fail)) + scale_fill_brewer(palette = "Spectral")
t + geom_histogram(aes(fill=factor(learn_about_study)), stat = "Identity",
                   bins=24,
                   col="black", 
                   size=.1) + # change number of bins
  # geom_density() + #this function is meant to draw a trend line for the graph
  # stat_bin(aes(y=count,label=count),geom="text",vjust=-.5) +   # this will display the total count of each bin
  labs(title="Number of Passed participants per month per encounter type", 
       subtitle="from july of 2017-January 2019",
       x="Date(Year-Month)",
       y="Count",
       fill="How did you learn about the study") +
  theme(axis.text.x = element_text(angle=70, vjust =.6))
```

```{r, echo=FALSE}
# Display the number of participants that passed the screening each month for Social Media
social_pass <- ds_some_rows_v1%>%
  select(int_phone_pass_fail,learn_about_study,encounter_date_int)%>%
  separate(encounter_date_int,c("y","m","d"))%>%
  filter(learn_about_study=="Facebook", int_phone_pass_fail==1)%>%
  group_by(m,y,int_phone_pass_fail)%>%
  summarize(count=n())%>%
  unite("YM",c("y","m"),sep ="-")

print(social_pass)

g <- ggplot(social_pass, aes(YM, count))
g + geom_bar(stat="identity", width = 0.5, fill="tomato2") + 
  labs(title="Social Media Pass participants", 
       x="Date(Year-Month)",
       y="count") +
  theme(axis.text.x = element_text(angle=65, vjust=0.6))

# Display the number of participants that passed the screening each month for Flyers
flyer_pass <- ds_some_rows_v1%>%
  select(int_phone_pass_fail,learn_about_study,encounter_date_int)%>%
  separate(encounter_date_int,c("y","m","d"))%>%
  filter(learn_about_study=="Flyer", int_phone_pass_fail==1)%>%
  group_by(m,y,int_phone_pass_fail)%>%
  summarize(count=n())%>%
  unite("YM",c("y","m"),sep ="-")

print(flyer_pass)

g <- ggplot(flyer_pass, aes(YM, count))
g + geom_bar(stat="identity", width = 0.5, fill="tomato2") + 
  labs(title="Flyer Pass participants", 
       x="Date(Year-Month)",
       y="count") +
  theme(axis.text.x = element_text(angle=65, vjust=0.6))



```


##Figures of Encounters with Consented Participants

```{r, echo=FALSE}
# Provides a filter to the data to view how particpnats heard about the study AND consented. Showed greater favor for Facebook recruitment.

Consent_per_Time <- ds_some_rows_v1%>%
  separate(encounter_date_int,c("y","m","d"))%>%
  filter(int_consent_complete==1)%>%
  group_by(learn_about_study_int,m,y)%>%
  summarize(count=n())%>%
  unite("YM",c("y","m"),sep ="-")


theme_set(theme_classic())

# distribution of visits each month(histogram)
h <- ggplot(Consent_per_Time, aes(YM, count)) + scale_fill_brewer(palette = "Spectral")
h + geom_histogram(aes(fill=factor(learn_about_study_int)), stat = "Identity",
                   bins=24,
                   col="black", 
                   size=.1) + # change number of bins
  #geom_text(aes(y=label_count,label=count), vjust=-.02) +  #doesn't work properly because cummulative sums aren't calulated 
  # geom_density() + #this function is meant to draw a trend line for the graph
  # stat_bin(aes(y=count,label=count),geom="text",vjust=-.5) +   # this will display the total count of each bin
  labs(title="How participants heard of our study monthly", 
       subtitle="from july of 2017-January 2019 and Have completed consent",
       x="Date(Year-Month)",
       y="Count",
       fill="How did you learn about the study") +
  theme(axis.text.x = element_text(angle=70, vjust =.6))


# Display the number of participants that passed the consent each month, Flyers

flyer_pass_consent <- ds_some_rows_v1%>%
  select(learn_about_study_int,encounter_date_int,int_consent_complete)%>%
  separate(encounter_date_int,c("y","m","d"))%>%
  filter(learn_about_study_int==1, int_consent_complete==1)%>%
  group_by(m,y,int_consent_complete)%>%
  summarize(count=n())%>%
  unite("YM",c("y","m"),sep ="-")

print(flyer_pass_consent)

g <- ggplot(flyer_pass_consent, aes(YM, count))
g + geom_bar(stat="identity", width = 0.5, fill="tomato2") + 
  labs(title="Flyer Consented Participants", 
       x="Date(Year-Month)",
       y="count") +
  theme(axis.text.x = element_text(angle=65, vjust=0.6))


# Display the number of participants that consented each month for Social Media
social_pass_consent <- ds_some_rows_v1%>%
  select(int_consent_complete,learn_about_study_int,encounter_date_int)%>%
  separate(encounter_date_int,c("y","m","d"))%>%
  filter(learn_about_study_int==3, int_consent_complete==1)%>%
  group_by(m,y,int_consent_complete)%>%
  summarize(count=n())%>%
  unite("YM",c("y","m"),sep ="-")

print(social_pass_consent)

g <- ggplot(social_pass_consent, aes(YM, count))
g + geom_bar(stat="identity", width = 0.5, fill="tomato2") + 
  labs(title="Social Media consented participants", 
       x="Date(Year-Month)",
       y="count") +
  theme(axis.text.x = element_text(angle=65, vjust=0.6))


```

###test
```{r}


```

##demographics
###Maternal Age of participants
```{r, echo=FALSE ,fig.cap= "Fig1: test"}
#select all the maternal ages and remove NA values:

Mat_age <- ds_some_rows_v1%>%
  select(record_id,analysis_mat_age,learn_about_study)%>%
  filter(!is.na(analysis_mat_age))%>%
  filter(!is.na(learn_about_study))
  
print(Mat_age)

#create a marginal Histogram / Boxplot for maternal ages by encounter type:
Mat_age$learn_about_study <- as.factor(Mat_age$learn_about_study)

    library(ggplot2)
  theme_set(theme_classic())
  
  # Plot
  g <- ggplot(Mat_age, aes(learn_about_study, analysis_mat_age))
  g + geom_boxplot(varwidth=T, fill="plum") + 
      labs(title="Age of Participants", 
           subtitle="Divided into how they heard of the study",
           caption="Source: BEACH Interview",
           x="How did you hear of our study",
           y="Age(years)")
  
```
  
  
###BMI of Participants
```{r, echo=FALSE, fig.cap="Fig2:BMI"}
  #Determining the average BMI per enocunter type.  
Pre_BMI <- ds_some_rows_v1%>%
  select(record_id,analysis_bmi,learn_about_study_int)%>%
  filter(!is.na(analysis_bmi))%>%
  filter(!is.na(learn_about_study_int))
  
print(Pre_BMI)

#create a marginal Histogram / Boxplot for maternal ages by encounter type:
Pre_BMI$learn_about_study_int <- as.factor(Pre_BMI$learn_about_study_int)

    library(ggplot2)
  theme_set(theme_classic())
  
  # Plot
  g <- ggplot(Pre_BMI, aes(learn_about_study_int, analysis_bmi))
  g + geom_boxplot(varwidth=T, fill="plum") + 
      labs(title="BMI of participants", 
           subtitle="Divided into how they heard of the study",
           caption="Source: BEACH Interview",
           x="How did you hear of our study",
           y="BMI")
  
  #Presenting amount of participnats per encounter per BMI catagories
Pre_BMI_L25 <- ds_some_rows_v1%>%
  select(record_id,analysis_bmi,learn_about_study_int)%>%
  filter(!is.na(analysis_bmi))%>%
  filter(!is.na(learn_about_study_int))%>%
  filter(analysis_bmi<25)%>%
  group_by(learn_about_study_int, analysis_bmi)%>%
  summarise(count=n())

Pre_BMI_between <- ds_some_rows_v1%>%
  select(record_id,analysis_bmi,learn_about_study_int)%>%
  filter(!is.na(analysis_bmi))%>%
  filter(!is.na(learn_about_study_int))%>%
  filter(analysis_bmi>25 & analysis_bmi<30)%>%
  group_by(learn_about_study_int, analysis_bmi)%>%
  summarise(count=n())


Pre_BMI_H30 <- ds_some_rows_v1%>%
  select(record_id,analysis_bmi,learn_about_study_int)%>%
  filter(!is.na(analysis_bmi))%>%
  filter(!is.na(learn_about_study_int))%>%
  filter(analysis_bmi>30)%>%
  group_by(learn_about_study_int, analysis_bmi)%>%
  summarise(count=n())


  #graph BMI groups per encounter



g <- ggplot(Pre_BMI_L25, aes(x=learn_about_study_int,y=count,fill=analysis_bmi))
g + geom_bar(stat="identity", width = 0.5) + geom_text(aes(label=count),vjust=-0.2) + 
      labs(title="Distribution of participants with BMI<25", 
           subtitle="Catagorized by How Particiapnt Heard of Study", 
           caption="Source: BEACH Interview study") 

g <- ggplot(Pre_BMI_between, aes(x=learn_about_study_int,y=count,fill=analysis_bmi))
g + geom_bar(stat="identity", width = 0.5) + geom_text(aes(label=count),vjust=-0.2) + 
      labs(title="Distribution of participants with BMI between 25 and 30", 
           subtitle="Catagorized by How Particiapnt Heard of Study", 
           caption="Source: BEACH Interview study") 

g <- ggplot(Pre_BMI_H30, aes(x=learn_about_study_int,y=count,fill=analysis_bmi))
g + geom_bar(stat="identity", width = 0.5) + geom_text(aes(label=count),vjust=-0.2) + 
      labs(title="Distribution of participants with BMI>30", 
           subtitle="Catagorized by How Particiapnt Heard of Study", 
           caption="Source: BEACH Interview study") 

#Level of education between participants
```

###Education Level of participants
```{r, echo=FALSE, fig.cap="Fig3.Education"}
Education <- ds_some_rows_v1%>%
  select(record_id,education_level)%>%
  filter(!is.na(education_level))%>%
  group_by(education_level)%>%
  summarise(count=n())

g <- ggplot(Education, aes(education_level, count))
g + geom_bar(stat="identity", width = 0.5, fill="tomato2") + 
      labs(title="Education level of participants", 
           subtitle="Catagorized by How Participant Heard of Study", 
           caption="Source: BEACH Interview study") +
  geom_text(aes(label=count),vjust=-0.2) +
      theme(axis.text.x = element_text(angle=65, vjust=0.6)) 


Education_encounter <- ds_some_rows_v1%>%
  select(record_id,education_level,learn_about_study)%>%
  filter(!is.na(education_level))%>%
  filter(!is.na(learn_about_study))%>%
  group_by(education_level,learn_about_study)%>%
  summarise(count=n())


    
theme_set(theme_classic())

# distribution of visits each month(histogram)
h <- ggplot(Education_encounter, aes(learn_about_study, count)) + scale_fill_brewer(palette = "Spectral")
h + geom_histogram(aes(fill=factor(education_level)), stat = "Identity",
                   bins=24,
                   col="black", 
                   size=.1) + # change number of bins
  # geom_density() + #this function is meant to draw a trend line for the graph
  #geom_text(aes(y=count,label=count), colour="black") +   # this will display the total count of each bin
  labs(title="Education level of participants per encounter type", 
       subtitle="from july of 2017-January 2019",
       x="encounter type",
       y="Count",
       fill="level of education") +
  theme(axis.text.x = element_text(angle=70, vjust =.6))
```

###Income Breakdown
```{r, echo=FALSE,fig.cap="fig4.Income"}

#total income levels of participants 
income_level <- ds_some_rows_v1%>%
  select(income,record_id,learn_about_study)%>%
  filter(!is.na(income))%>%
  filter(!is.na(learn_about_study))%>%
  group_by(income)%>%
  summarise(count=n())



g <- ggplot(income_level, aes(income, count))
g + geom_bar(stat="identity", width = 0.5, fill="tomato2") + 
      labs(title="Income levels of Participants", 
           caption="Source: BEACH Interview study") +
  geom_text(aes(label=count),vjust=0.9) +
      theme(axis.text.x = element_text(angle=65, vjust=0.6)) 


#Histogram of income levels of participants 
income_level <- ds_some_rows_v1%>%
  select(income,record_id,learn_about_study)%>%
  filter(!is.na(income))%>%
  filter(!is.na(learn_about_study))%>%
  group_by(income,learn_about_study)%>%
  summarise(count=n())

theme_set(theme_classic())

# distribution of visits each month(histogram)
h <- ggplot(income_level, aes(learn_about_study, count)) + scale_fill_brewer(palette = "Spectral")
h + geom_histogram(aes(fill=factor(income)), stat = "Identity",
                   bins=24,
                   col="black", 
                   size=.1) + # change number of bins
  # geom_density() + #this function is meant to draw a trend line for the graph
  #geom_text(aes(y=count,label=count), colour="black") +   # this will display the total count of each bin
  labs(title="Income Levels of Participants Per Encounters", 
       subtitle="from july of 2017-January 2019",
       x="encounter type",
       y="Count",
       fill="Income Level") +
  theme(axis.text.x = element_text(angle=70, vjust =.6))

```


###Preganent and Nonpregnant Participant Breakdown
```{r, echo=FALSE, fig.cap="fig6.Birth/pregnant"}
A_Preg <- ds_some_rows_v1%>%
  select(record_id,learn_about_study)%>%
  slice(57:84)%>%
  group_by(learn_about_study)%>%
  summarise(count=n())
print(A_Preg)

g <- ggplot(A_Preg, aes(learn_about_study, count))
g + geom_bar(stat="identity", width = 0.5, fill="tomato2") + 
      labs(title="How Participant After Birth heard of our study", 
           subtitle="only consented participnats", 
           caption="Source: BEACH Interview study") +
  geom_text(aes(label=count),vjust=-0.2) +
      theme(axis.text.x = element_text(angle=65, vjust=0.6)) 

C_Preg <- ds_some_rows_v1%>%
  select(record_id,learn_about_study)%>%
  slice(85:103)%>%
  group_by(learn_about_study)%>%
  summarise(count=n())
print(C_Preg)

g <- ggplot(C_Preg, aes(learn_about_study, count))
g + geom_bar(stat="identity", width = 0.5, fill="tomato2") + 
      labs(title="how pregnant participants heard of our study", 
           subtitle="only consented participants", 
           caption="Source: BEACH Interview study") +
  geom_text(aes(label=count),vjust=-0.2) +
      theme(axis.text.x = element_text(angle=65, vjust=0.6)) 
```

##Reviewing encounters without time
```{r, echo=FALSE}
encounters <- ds_some_rows_v1%>%
  select(learn_about_study_int)%>%
  filter(!is.na(learn_about_study_int))%>%
  group_by(learn_about_study_int)%>%
  summarize(count=n())

g <- ggplot(encounters, aes(learn_about_study_int, count))
g + geom_bar(stat="identity", width = 0.5, fill="tomato2") + 
      labs(title="total of how participant learned about study", 
           subtitle="concented and nonconsented", 
           caption="Source: BEACH Interview study") +
  geom_text(aes(label=count),vjust=-0.2) +
      theme(axis.text.x = element_text(angle=65, vjust=0.6)) 


encounters_consent <- ds_some_rows_v1%>%
  select(learn_about_study_int,int_consent_complete)%>%
  filter(!is.na(learn_about_study_int))%>%
  replace_na(int_consent_complete=0)%>%
  group_by(learn_about_study_int, int_consent_complete)%>%
  summarise(count=n())


g <- ggplot(encounters_consent, aes(x=learn_about_study_int,y=count,fill=int_consent_complete))
g + geom_bar(stat="identity", width = 0.5) + geom_text(aes(label=count),vjust=-0.2) + 
      labs(title="total of how participant learned about study", 
           subtitle="concented and nonconsented", 
           caption="Source: BEACH Interview study") 




```